site_name: OpenL Tablets
site_url: https://example.com/
nav:
    - Home: index.md
    - Level: 
        - News: news.md
        - What is OpenL Tablets?: whatis.md
        - Test: 'test/test01.md'
        - Documentaion: documentation.md'
theme: readthedocs
