site_name: OpenL Tablets
site_url: https://example.com/
nav:
    - Home: index.md 
    - News: news.md
    - What is OpenL Tablets?: whatis.md
    - Features: features.md
    - Supported Platforms: platforms.md
    - Downloads: downloads.md
    - Release Notes: 
        - releasenotes/latest_rn.md
        - releasenotes/all_rn.md
    - Documentation:
        - Available docs: documentation.md
        - Installation Guide: installationguide.md
    - Test: 'test/test01.md'
theme: readthedocs

markdown_extensions:
  - markdown.extensions.admonition
