site_name: OpenL Tablets
site_url: https://example.com/
nav:
    - Home: index.md
    - Level: 
        - News: news.md
        - What is OpenL Tablets?: whatis.md
        - Features: features.md
        - Supported Platforms: platforms.md
        - 
        - Downloads: downloads.md
        - Documentation: documentation.md
        - Test: 'test/test01.md'
theme: readthedocs

markdown_extensions:
  - markdown.extensions.admonition
