site_name: OpenL Tablets
site_url: https://example.com/
nav:
    - Home: index.md 
    - News: news.md
    - What is OpenL Tablets?: whatis.md
    - Features: features.md
    - Supported Platforms: platforms.md
    - Downloads: downloads.md
    - Release Notes: 
        - Latest Release: releasenotes/latest_rn.md
        - Previous Releases: releasenotes/all_rn.md
        - Migration Notes: releasenotes/migration_notes.md
    - Documentation:
        - Available docs: documentation.md
        - Guides:
            - Latest Guides: guides/latest_guides.md
            - Previous Guides: guides/previous_guides.md
    - Test: 'test/test01.md'
theme: readthedocs

markdown_extensions:
  - markdown.extensions.admonition
